site_name: Diffusion PushT
repo_url: https://github.com/mutichung/diffusion_pusht
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.indexes

  logo: assets/logo.png

plugins:
  - blog:
      blog_dir: logs
      post_date_format: full
  - search
  - mkdocs-jupyter

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - Welcome: index.md
    - setup.md
  - Methodology:
    - methodology/diffusion.md
    - methodology/model_architecture.md
  - Experiments:
    - experiments/setup.md
    - experiments/data_analysis.ipynb
    - Results & Analysis: experiments/results.md
  - Logs:
    - logs/index.md

copyright: Logo by YANDI RS from <a href="https://thenounproject.com/browse/icons/term/robotic-arm/" target="_blank" title="Robotic arm Icons">Noun Project</a> (CC BY 3.0)